### ISSUE TITLE
【Question】Unknown column 'id' in 'where clause'

### ISSUE THREAD

**Issue by koichi-oshima** [nishio-dens/gamma#10]
すみません、質問させて頂きたくissue作成しました。
テーブル名を指定して同期する検証しており、dry run 実行時にエラーが表示されるのですが、primarykeyが🆔以外の場合はどこかで明示的に設定する必要があるのでしょうか。

```
ERROR -- : Sync Error <table_name>
 Unknown column 'id' in 'where clause'
```

**Comment by nishio-dens** [comment]
PrimaryKeyをid以外にするオプションは、今はサポートしておりません。
該当箇所は https://github.com/nishio-dens/gamma/blob/master/lib/gamma/importer/replace.rb#L23 です。

**Comment by koichi-oshima** [comment]
@nishio-dens 
承知致しました。
早速のご回答ありがとうございました。
